app/models.py
from datetime import datetime
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from app import login
from flask_login import UserMixin
from hashlib import md5


# flask-login: user loader function
@login.user_loader
def load_user(id):
    return User.query.get(int(id))


followers = db.Table("followers",
    db.Column("follower_id", db.Integer, db.ForeignKey("user.id")),
    db.Column("followed_id", db.Integer, db.ForeignKey("user.id"))
)


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship("Post", backref="author", lazy="dynamic")
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)

    followed = db.relationship(
        "User", secondary=followers,  # main table, secondary table
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        backref=db.backref("followers", lazy="dynamic"), lazy="dynamic"
    )

    def followed_posts(self):
        return Post.query.join(
            # post join followers on followed_id == user_id
            followers, (followers.c.followed_id == Post.user_id)).filter(
                # 
                followers.c.follower_id == self.id).order_by(  # filter all posts of that followers
                    Post.timestamp.desc())

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(
            followers.c.followed_id == user.id).count() > 0

    def set_password(self, password):
        """ hash the user's password"""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return "<user {}>".format(self.username)

    def avatar(self, size=128):
        digest = md5(self.email.lower().encode("utf-8")).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, size)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __repr__(self):
        return "<Post {}>".format(self.body)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,  SubmitField
from wtforms import TextAreaField
from wtforms.validators import DataRequired
from wtforms.validators import ValidationError, Length

from app.models import User


class EditProfileForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    about_me = TextAreaField("About me", validators=[Length(min=0, max=140)])
    submit = SubmitField("Submit")

    def __init__(self, original_username, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                raise ValidationError("Please use a different username.")

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
import logging
from logging.handlers import RotatingFileHandler
import os


# define extensions
db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = "auth.login"


# factory pattern
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix="/auth")

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler(
            'logs/microblog.log', maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Microblog startup')

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from app.models import User
from datetime import datetime
from app.main import bp
from app.main.forms import EditProfileForm
from app import db


@bp.route("/seba")
def seba():
    return "seba!!!"


@bp.route("/")
@bp.route('/index')
@login_required
def index():
    # # fake news
    posts = [{
        "author": current_user,
        "body": "what a beautiful place"
    }, {
        "author": current_user,
        "body": "this is a great post about..."
    }]
    return render_template(
        "index.html", title="home", posts=posts)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    # making temporary fake posts
    posts = [
        {"author": user, "body": "test post #1"},
        {"author": user, "body": "test post #2"},
    ]
    return render_template("user.html", user=user, posts=posts)


@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username)
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash("Your changes have been saved.")
        return redirect(url_for("main.edit_profile"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    return render_template(
        "edit_profile.html", title="Edit Profile", form=form)


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

app/templates/_post.html
<div class="post">
  <img src="{{post.author.avatar(30)}}" alt="{{post.author.username}}">
  <span>{{post.author.username}} says: <b>{{post.body}}</b></span>
</div>

app/templates/base.html
<html>
  <head>
    {% if title%}
      <title>{{ title }} - Megablog</title>
    {% else %}
      <title>Welcome to Megablog</title>
    {% endif %}
  </head>
  <body>
    <div>MegaBlog:
      <a href="{{ url_for('main.index') }}">Home</a>
      {% if current_user.is_anonymous %}
      <a href="{{ url_for('auth.login') }}">Login</a>
      {% else %}
      <a href="{{ url_for("main.user", username=current_user.username) }}">Profile</a>
      <a href="{{ url_for('auth.logout')}}">Logout</a>
      {% endif%}
    <hr>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
          {% for message in messages %}
            <li>{{message}}</li>
          {% endfor %}
        </ul>
        {% endif %}
      {% endwith %}

    {% block content %}{% endblock content %}
  </body>
</html>

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
  <h1>Edit Profile</h1>
  <form action="" method="post">
    {{form.hidden_tag()}}
    <p>
      {{form.username.label}}<br>
      {{form.username(size=32)}}
      {% for error in form.username.errors %}
        <span style="color:red;">[{{error}}]</span>
      {% endfor %}
    </p>
    <p>
      {{form.about_me.label}}<br>
      {{form.about_me(cols=50, rows=4)}}<br>
      {% for error in form.about_me.errors %}
        <span style="color:red;">[{{error}}]</span>
      {% endfor %}
    </p>
    <p>{{form.submit}}</p>
  </form>
{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

  <h1>Hey, {{current_user.username}}!</h1>
  {% for post in posts %}
    {% include "_post.html" %}
  {% endfor %}

{% endblock content %}

app/templates/user.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <img src="{{user.avatar()}}" alt="avatar">
    <h1>User: {{user.username}}</h1>
      {% if user.about_me %}
        <p>{{user.about_me}}</p>
      {% endif %}
      {% if user.last_seen %}
        <p>Last seen on: {{user.last_seen}}</p>
      {% endif %}
      {% if user == current_user %}
        <p><a href="{{url_for("main.edit_profile")}}">Edit your profile</a></p>
      {% endif %}
  </div>
  <hr>
  {% for post in posts %}
    {% include "_post.html" %}
  {% endfor %}
{% endblock content %}